### ISSUE TITLE
Import of required libraries not working

### ISSUE THREAD

**Issue by sepastian** [helgeho/ArchiveSpark-docker#1]
After successfully starting the ArchiveSpark Docker container and creating an empty notebook according to [general usage instructions](https://github.com/helgeho/ArchiveSpark/blob/master/docs/General_Usage.md), importing required libraries fails with `[init] error: error while loading <root>, Error accessing /config/lib/archivespark-assembly-2.7.6-deps.jar` (full error below).

The docker container has been started successfully with this.

```bash
docker run --rm -ti \
       -v $(readlink -m config):/config \
       -v $(readlink -m notebooks):/notebooks \
       -v $(readlink -m $(dirname $0)/../../data):/data \
       -p 8888:8888 helgeho/archivespark
```

A notebook has been created, it contains the following.

```python3
import de.l3s.archivespark._
import de.l3s.archivespark.implicits._
import de.l3s.archivespark.enrich.functions._
import de.l3s.archivespark.specific.warc.implicits._
import de.l3s.archivespark.specific.warc.specs._
import de.l3s.archivespark.specific.warc.enrichfunctions._
```

The cell fails to execute with the error message below (docker window).

```
[I 10:34:54.922 NotebookApp] Kernel started: c6214e70-31c8-4dee-bc62-0a313a8bcb14
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
18/09/12 10:34:55 [INFO] o.a.t.Main$$anon$1 - Kernel version: 0.2.0.dev1-incubating-SNAPSHOT
18/09/12 10:34:55 [INFO] o.a.t.Main$$anon$1 - Scala version: Some(2.11.8)
18/09/12 10:34:55 [INFO] o.a.t.Main$$anon$1 - ZeroMQ (JeroMQ) version: 3.2.2
18/09/12 10:34:55 [INFO] o.a.t.Main$$anon$1 - Initializing internal actor system
18/09/12 10:34:55 [INFO] o.a.t.Main$$anon$1 - Connection Profile: {
  "stdin_port" : 46887,
  "control_port" : 58955,
  "hb_port" : 33727,
  "shell_port" : 34439,
  "iopub_port" : 38473,
  "ip" : "127.0.0.1",
  "transport" : "tcp",
  "signature_scheme" : "hmac-sha256",
  "key" : "b42e880d-538d5fd81e17b149fad311dd"
}
(Scala,org.apache.toree.kernel.interpreter.scala.ScalaInterpreter@6bab2585)
(PySpark,org.apache.toree.kernel.interpreter.pyspark.PySparkInterpreter@74bdc168)
(SparkR,org.apache.toree.kernel.interpreter.sparkr.SparkRInterpreter@644c78d4)
(SQL,org.apache.toree.kernel.interpreter.sql.SqlInterpreter@532a02d9)
18/09/12 10:34:56 [INFO] o.a.t.k.p.v.r.KernelMessageRelay - Not ready for messages! Stashing until ready!
18/09/12 10:34:56 [WARN] o.a.t.Main$$anon$1 - No external magics provided to PluginManager!
18/09/12 10:34:59 [INFO] o.a.t.Main$$anon$1 - 13 internal plugins loaded
18/09/12 10:34:59 [INFO] o.a.t.Main$$anon$1 - 0 external plugins loaded
18/09/12 10:34:59 [INFO] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Setting deployMode to client
18/09/12 10:34:59 [WARN] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Locked to Scala interpreter with SparkIMain until decoupled!
18/09/12 10:34:59 [WARN] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Unable to control initialization of REPL class server!
18/09/12 10:34:59 [WARN] o.a.h.u.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/09/12 10:35:00 [INFO] o.a.t.b.l.StandardComponentInitialization$$anon$1 - Connecting to spark.master local[*]
[init] error: error while loading <root>, Error accessing /config/lib/archivespark-assembly-2.7.6-deps.jar

Failed to initialize compiler: object java.lang.Object in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programmatically, settings.usejavacp.value = true.

Failed to initialize compiler: object java.lang.Object in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programmatically, settings.usejavacp.value = true.
Exception in thread "main" java.lang.NullPointerException
	at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:256)
	at scala.tools.nsc.interpreter.IMain$Request.x$20$lzycompute(IMain.scala:896)
	at scala.tools.nsc.interpreter.IMain$Request.x$20(IMain.scala:895)
	at scala.tools.nsc.interpreter.IMain$Request.headerPreamble$lzycompute(IMain.scala:895)
	at scala.tools.nsc.interpreter.IMain$Request.headerPreamble(IMain.scala:895)
	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.preamble(IMain.scala:918)
	at scala.tools.nsc.interpreter.IMain$CodeAssembler$$anonfun$apply$23.apply(IMain.scala:1337)
	at scala.tools.nsc.interpreter.IMain$CodeAssembler$$anonfun$apply$23.apply(IMain.scala:1336)
	at scala.tools.nsc.util.package$.stringFromWriter(package.scala:64)
	at scala.tools.nsc.interpreter.IMain$CodeAssembler$class.apply(IMain.scala:1336)
	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.apply(IMain.scala:908)
	at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:1002)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:997)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:579)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$start$1.apply(ScalaInterpreterSpecific.scala:295)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$start$1.apply(ScalaInterpreterSpecific.scala:289)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:214)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$class.start(ScalaInterpreterSpecific.scala:289)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreter.start(ScalaInterpreter.scala:43)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreter.init(ScalaInterpreter.scala:86)
	at org.apache.toree.boot.layer.InterpreterManager$$anonfun$initializeInterpreters$1.apply(InterpreterManager.scala:35)
	at org.apache.toree.boot.layer.InterpreterManager$$anonfun$initializeInterpreters$1.apply(InterpreterManager.scala:34)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at org.apache.toree.boot.layer.InterpreterManager.initializeInterpreters(InterpreterManager.scala:34)
	at org.apache.toree.boot.layer.StandardComponentInitialization$class.initializeComponents(ComponentInitialization.scala:90)
	at org.apache.toree.Main$$anon$1.initializeComponents(Main.scala:35)
	at org.apache.toree.boot.KernelBootstrap.initialize(KernelBootstrap.scala:101)
	at org.apache.toree.Main$.delayedEndpoint$org$apache$toree$Main$1(Main.scala:40)
	at org.apache.toree.Main$delayedInit$body.apply(Main.scala:24)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.apache.toree.Main$.main(Main.scala:24)
	at org.apache.toree.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[W 10:35:04.946 NotebookApp] Timeout waiting for kernel_info reply from c6214e70-31c8-4dee-bc62-0a313a8bcb14
18/09/12 10:35:04 [INFO] o.a.t.k.p.v.r.KernelMessageRelay - Not ready for messages! Stashing until ready!
18/09/12 10:35:04 [WARN] o.a.t.k.p.v.k.s.Shell - Parent header is null for message b41872bc8c4744dd8c7aed8b0022e017 of type comm_info_request
18/09/12 10:35:04 [INFO] o.a.t.k.p.v.r.KernelMessageRelay - Not ready for messages! Stashing until ready!
```

I have read elsewhere that Spark does not work with Java 9, but that doesn't seem to be the issue here, I checked the Java version inside the container.

```
$ docker exec -it hungry_mirzakhani /bin/bash
root@8c773e9e4390:/# java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

What could be the issue here?

**Comment by helgeho** [comment]
Thanks for pointing this out, there was actually a typo in the ArchiveSpark release path, which accidentally changed with the latest version. I've just corrected it and that fixed the issue.

To make it work for you, please remove the image `docker rmi helgeho/archivespark` and delete the `lib` folder in your `config` dir, then run it again. Sorry about that!
