### ISSUE TITLE
warc.peekJson - IllegalAccessError

### ISSUE THREAD

**Issue by sepastian** [helgeho/ArchiveSpark-docker#2]
Thanks for fixing #1, it works now! Here is another one.

```
import de.l3s.archivespark._
import de.l3s.archivespark.implicits._
import de.l3s.archivespark.enrich.functions._
import de.l3s.archivespark.specific.warc.implicits._
import de.l3s.archivespark.specific.warc.specs._
import de.l3s.archivespark.specific.warc.enrichfunctions._

val warcPath = "/data/dfi7eyi3xbde6s2w-20180829145723.warc.gz"
val warc = ArchiveSpark.load(WarcGzHdfsSpec(warcPath))
warc.peekJson
```

When invoking `warc.peekJson`, the following exception occurs.

```
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat
  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:379)
  at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:125)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1333)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.take(RDD.scala:1327)
  at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1368)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.first(RDD.scala:1367)
  at de.l3s.archivespark.implicits.classes.GenericHelpersRDD.peek(GenericHelpersRDD.scala:33)
  at de.l3s.archivespark.implicits.classes.JsonConvertibleRDD.peekJson(JsonConvertibleRDD.scala:45)
  ... 64 elided
18/09/12 17:47:16 [WARN] o.a.t.k.p.v.s.KernelOutputStream - Suppressing empty output: ''
```

[Someone pointed out](https://stackoverflow.com/questions/36427291/illegalaccesserror-to-guavas-stopwatch-from-org-apache-hadoop-mapreduce-lib-inp) that updating `hadoop-mapreduce-client-core` to 2.7.2 may help.

**Comment by helgeho** [comment]
This seems to be a compatibility issue with the Spark version of the docker image and the latest ArchiveSpark release (I don't use the docker container, but have ArchiveSpark installed on a cluster, which is why we did not notice it). But it should be fixed now.

Please remove your image once more `docker rmi helgeho/archivespark` and delete the `spark` folder in your config dir, then run it again. Hope this helps!
